spring:
  application:
    name: geminitest
  config:
    import: optional:file:.env[.properties]
  ai:
    chat:
      observations:
        log-prompt: false
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.5-flash
          temperature: 0.0
      embedding:
        api-key: ${GEMINI_API_KEY}
        base-url: https://generativelanguage.googleapis.com/v1beta/openai
        options:
          model: text-embedding-004
          dimensions: 768
        embeddings-path: /embeddings
    vectorstore:
      simple:
        store:
          path: ./vectorstore.json
  datasource:
    url: jdbc:postgresql://localhost:5432/geminitest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.ai: DEBUG
    org.postgresql: DEBUG