spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: geminitest
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash
  datasource:
    url: jdbc:postgresql://localhost:5432/geminitest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.ai: DEBUG
    org.postgresql: DEBUG